# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-27 01:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, b'Lunes'), (2, b'Martes'), (3, b'Miercoles'), (4, b'Jueves'), (5, b'Viernes'), (6, b'Sabado')], default=1)),
                ('descripcion', models.CharField(max_length=50)),
                ('hora_inicio', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)])),
                ('hora_fin', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)])),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField(choices=[(1, b'Disponible'), (2, b'No Disponible'), (3, b'Reservada'), (4, b'Confirmada')], default=1)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='sala.Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('capacidad', models.SmallIntegerField()),
                ('horarios', models.ManyToManyField(through='sala.HorarioSala', to='sala.Horario')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='horariosala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='sala.Sala'),
        ),
    ]
